CREATE TABLE [dbo].[APODERADO]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Nombre] NCHAR(10) NOT NULL, 
    [Telefono] NCHAR(10) NOT NULL, 
    [Id_alumno] NCHAR(10) NOT NULL, 
    CONSTRAINT [FK_APODERADO_ALUMNOS] FOREIGN KEY ([Id_alumno]) REFERENCES [ALUMNOS]([Id])
)
