CREATE TABLE [dbo].[INSCRITOS]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Id_Alumno] INT NOT NULL, 
    [Cod_curso] INT NOT NULL, 
    CONSTRAINT [FK_INSCRITOS_ALUMNOS] FOREIGN KEY ([Id_Alumno]) REFERENCES [ALUMNOS]([Id]), 
    CONSTRAINT [FK_INSCRITOS_CURSOS] FOREIGN KEY ([Cod_curso]) REFERENCES [CURSOS]([COD]), 
)
